import Rhino
import rhinoscriptsyntax as rs
import scriptcontext as sc
 
 
#Add point objects at stacked control point locations.
def StackedPoints():
    count = 0
    Ids = rs.GetObjects("Select curves or surfaces to test.", filter = 4 + 8, preselect=True)
    
    if not Ids:return
    dups = []
    for Id in Ids:
        
        if rs.IsSurface(Id):
            
            pts = sc.doc.Objects.Find(Id).Geometry.Surfaces[0].Points
        else:
            pts  = sc.doc.Objects.Find(Id).Geometry.Points 
 
        G = list(pts)
        ploc = []
        for g in G:
            ploc.append(g.Location)
 
        for pt in ploc:
            if ploc.count(pt) > 1:
                dups.append(pt)
 
    if len(dups) > 1:
        dups = set(dups)
        pList = []
        for pt in dups:
            pList.append(sc.doc.Objects.AddPoint(pt))
        if len(pList) > 0: rs.SelectObjects(pList)
    sc.doc.Views.Redraw()
 
StackedPoints()
